# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeff Appareti - Web Developer and Designer Santa Barbara California
email: jappareti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a rare hybrid of developer &amp; designer. I have been helping businesses, 
  individuals and non-profits with their websites for over 8 years. I design 
  responsive clean websites that successfully sell products, advertise services, 
  or clarify missions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jeffappareti.com" # the base hostname & protocol for your site
twitter_username: jappareti
github_username:  jappareti

# Build settings
markdown: kramdown
